#! /bin/sh
#
# Script to check  if the bacnet router is working
# Chris Edwards - Nasstar - Dec 2016

OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "h?:H:U:P:" opt; do
    case "$opt" in
    h|\?)
        echo "   Check basnet usage:"
        echo "           -H <hostname> -U username -P password"         
        exit 0
        ;;
    H)  hostname=$OPTARG;;
    U)  user=$OPTARG;;
    P)  pass=$OPTARG;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

# Variables:
tmpfile=/tmp/bacnet-diag-$hostname.tmp

#get the diag output

rm  $tmpfile > /dev/null 2>&1
wget --user=$user --password=$pass http://$hostname/cgi-bin/diagnostic.cgi -O $tmpfile > /dev/null 2>&1


now=`sed '5q;d' $tmpfile | awk '{print $4}' | sed 's/.\{2\}$//'` > /dev/null 2>&1

# check if we have current data pasage

results=`fgrep $now  $tmpfile | fgrep bas-rt`

       # Return icinga/nagios results:

        if [ -z "$results" ] 
	        then
 	               echo " Bacnet Warning - $now - No current log data system may need to be restarted"
       		         exit 1
        	fi

        echo "Bacnet OK - $now Logs show current traffic"
        exit 0
